name: build

on:
  push:
    branches:
      - master
      - /^\d+\.\d+\.\d(-alpha\.\d+|-beta\.\d+|-rc\.\d+)?$/
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test, Build & Release
    runs-on: "ubuntu-latest"
    env:
      LOGS_DIR: /tmp/code-style/logs
      LOGS_FILE: /tmp/code-style/logs/build-perf.log
      NPM_VERSION: "8.x"
      TZ: "Europe/Brussels"
    steps:
      # See: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # See: https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Create file & folder for GitHub Actions logs
        run: |
          # cfr scripts/_ghactions-group.sh
          mkdir -p $LOGS_DIR
          touch $LOGS_FILE

      - name: Get tag name if exists
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed -n "s/^refs\/tags\/\(\S*\).*$/\1/p")
          echo "GH_ACTIONS_TAG=${TAG_NAME}" >> $GITHUB_ENV

      - name: List main variables
        run: |
          echo "Commit SHA  : ${GITHUB_SHA}"
          echo "Tag name    : ${GH_ACTIONS_TAG}"
          echo "Reference   : ${GITHUB_REF}"
          echo "Head branch : ${GITHUB_HEAD_REF}"
          echo "Base branch : ${GITHUB_BASE_REF}"
          echo "Build number: ${GITHUB_RUN_NUMBER}"
          echo "Repository  : ${GITHUB_REPOSITORY}"
          echo "Event       : ${GITHUB_EVENT_NAME}"
          echo "Author      : ${GITHUB_ACTOR}"
          NODE_VERSION="$(node -v)"
          echo "Node version: $NODE_VERSION"
          npm i -g npm@${NPM_VERSION}
          # This ensures that we are authenticated without requiring to have an actual .npmrc file within the project
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
        env:
          GH_ACTIONS_TAG: ${{ steps.get_tag_name.outputs.TAG_NAME }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      # See: https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v3
        with:
          name: dist-${{ github.run_id }}
          path: dist

      - name: Release
        run: npm run release:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save logs
        run: bash ./scripts/ci/print-logs.sh
